### ISSUE TITLE
Cosmos playground don't load custom font from bundle.

### ISSUE THREAD

**Issue by michaelkutuzov** [react-cosmos/react-cosmos#1034]
Good afternoon!
### What's wrong?
Cosmos playground don't load custom font from bundle.

### Steps to reproduce
I have font *Circe* in woff and woff2 formats. I use @font-face to include it in code base.
```scss
@font-face {
  font-family: 'Circe';
  src:
    url('_styles/fonts/Circe/Circe-ExtraLight.woff') format('woff'),
    url('_styles/fonts/Circe/Circe-ExtraLight.woff2') format('woff2');
  font-weight: extralight;
  font-style: normal;
}
```
**SCSS code of component**:
```scss
$circe: Circe, Arial, Helvetica, sans-serif;

.big {
  height: 54px;
  font: bold 18px / 22px $circe;
}
```
Here used postcss loader with plugin 
```js
"postcss-short-font-size": "^5.0.0",
```

All fonts add correctly in development and production mode, when I use my webpack config. But if I launch react-cosmos, it use only my local fonts and don't add Circe from bundle.

For example: It uses arial, if I change arial to Papyrus, it displays Papirus.

React cosmos launch by
```js
"start:styleguide": "babel-node node_modules/react-cosmos/bin/cosmos.js --config cosmos.config.json"
```

### User info
Server terminal output is empty
Browser console output is empty

**Cosmos version**
```js
^5.0.0-alpha.28"
```

**If bug occurred on upgrade**
no

**Cosmos config**
```js
{
  "port": 5555,
  "webpack": {
    "configPath": "./tools/webpack/config.babel.js"
  }
}
```
**webpack version**
```js
"^4.6.0"
```
**webpack config**
```js
/* eslint-disable */

import path from 'path';
import webpack from 'webpack';
import ManifestPlugin from 'webpack-manifest-plugin';
import OptimizeCSSAssetsPlugin from "optimize-css-assets-webpack-plugin";
import ExtractTextPlugin from 'extract-text-webpack-plugin';
import StyleLintPlugin from 'stylelint-webpack-plugin';
import CompressionPlugin from 'compression-webpack-plugin';
import ImageminPlugin from 'imagemin-webpack-plugin';
import FriendlyErrorsWebpackPlugin from 'friendly-errors-webpack-plugin';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
import SpriteLoaderPlugin from 'svg-sprite-loader/plugin';
// Especially for react-cosmos styleguide
// https://github.com/react-cosmos/react-cosmos/blob/master/NEXT.md
import HtmlWebpackPlugin from 'html-webpack-plugin';

const nodeEnv = process.env.NODE_ENV || 'development';
const appEnv = process.env.APP_ENV || 'development';
const injectHtml = process.env.HTML_INJECTION === 'inject';

const isDev = nodeEnv === 'development';
const CSSModules = true;
const eslint = false;
const stylelint = false;

const getPlugins = () => {
  const plugins = [
    new ExtractTextPlugin({
      filename: '[name].[chunkhash:8].css',
      allChunks: true,
      disable: isDev, // Disable css extracting on development
      ignoreOrder: CSSModules,
    }),
    new ManifestPlugin({
      fileName: path.resolve(process.cwd(), 'public/webpack-assets.json'),
      filter: file => file.isInitial
    }),
    new StyleLintPlugin({ failOnError: stylelint }),
    new webpack.EnvironmentPlugin({ NODE_ENV: JSON.stringify(nodeEnv) }),
    new webpack.DefinePlugin({
      __CLIENT__: true,
      __SERVER__: false,
      __DEV__: isDev,
      __INJECT_HTML__: injectHtml,
      __APP_ENV__: JSON.stringify(appEnv),
    }),
    new FriendlyErrorsWebpackPlugin(),
    new SpriteLoaderPlugin(),
    new HtmlWebpackPlugin({
      filename: 'index.html',
    }),
  ];

  if (isDev) {
    plugins.push(new webpack.HotModuleReplacementPlugin());
  } else {
    plugins.push(
      new webpack.HashedModuleIdsPlugin(),
      new CompressionPlugin({
        asset: '[path].gz[query]',
        algorithm: 'gzip',
        test: /\.jsx?$|\.css$|\.(scss|sass)$|\.html$/,
        threshold: 10240,
        minRatio: 0.8
      }),
      /*
      new ImageminPlugin({
        pngquant: { quality: '95-100' }
      }),
      */
      new BundleAnalyzerPlugin({
        analyzerMode: process.env.NODE_ENV === 'analyze' ? 'server' : 'disabled'
      })
    );
  }

  return plugins;
};

const getEntry = () => {
  if (!isDev) {
    return ['./src/client.js'];
  }

  return ['webpack-hot-middleware/client', './src/client.js'];
};

// Webpack configuration
module.exports = {
  mode: isDev ? 'development' : 'production',
  devtool: isDev ? 'cheap-module-source-map' : 'hidden-source-map',
  context: path.resolve(process.cwd()),
  entry: getEntry(),
  optimization: {
    minimizer: [
      new OptimizeCSSAssetsPlugin({})
    ],
  },
  output: {
    path: path.resolve(process.cwd(), 'public/assets'),
    publicPath: '/assets/',
    // Don't use chunkhash in development it will increase compilation time
    filename: isDev ? '[name].js' : '[name].[chunkhash:8].js',
    chunkFilename: isDev ? '[name].chunk.js' : '[name].[chunkhash:8].chunk.js',
    pathinfo: isDev
  },
  module: {
    rules: [
      {
        // Eslint
        enforce: 'pre',
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'eslint',
        options: { failOnError: eslint }
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        options: {
          cacheDirectory: isDev,
        },
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style',
          use: [
            {
              loader: 'css',
              options: {
                importLoaders: 1,
                sourceMap: true,
                modules: CSSModules,
                context: path.join(process.cwd(), './src'),
                localIdentName: '[name]__[local]--[hash:base64:5]',
                minimize: !isDev,
              },
            },
            { loader: 'postcss', options: { sourceMap: true } },
          ],
        }),
      },
      {
        test: /\.(scss|sass)$/,
        loader: ExtractTextPlugin.extract({
          fallback: 'style',
          use: [
            {
              loader: 'css',
              options: {
                importLoaders: 2,
                sourceMap: true,
                modules: CSSModules,
                context: path.join(process.cwd(), './src'),
                localIdentName: '[name]__[local]--[hash:base64:5]',
                minimize: !isDev,
              },
            },
            { loader: 'postcss', options: { sourceMap: true } },
            {
              loader: 'sass',
              options: {
                outputStyle: 'expanded',
                sourceMap: true,
                sourceMapContents: !isDev,
              },
            },
          ],
        }),
      },
      {
        test: /\.(woff2?|ttf|eot)$/,
        loader: 'url',
        options: { limit: 10240, name: '[name].[hash:8].[ext]' }
      },
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        options: {
          extract: true,
          esModule: false,
        }
      },
      {
        test: /\.(gif|png|jpe?g|webp)$/,
        // Any image below or equal to 10K will be converted to inline base64 instead
        loader: 'url',
        options: { name: '[name].[hash:8].[ext]' }
      }
    ]
  },
  plugins: getPlugins(),
  /* Advanced configuration */
  resolveLoader: {
    // Use loaders without the -loader suffix
    moduleExtensions: ['-loader']
  },
  resolve: {
    modules: ['src', 'node_modules'],
    descriptionFiles: ['package.json'],
    alias: {
      _redux: path.resolve(process.cwd(), 'src/_redux'),
      _utils: path.resolve(process.cwd(), 'src/utils'),
      _api: path.resolve(process.cwd(), 'src/api'),
      _hocs: path.resolve(process.cwd(), 'src/hocs'),
      _config: path.resolve(process.cwd(), 'src/config'),
      _store: path.resolve(process.cwd(), 'src/store'),
      _pages: path.resolve(process.cwd(), 'src/pages'),
      _containers: path.resolve(process.cwd(), 'src/containers'),
      _components: path.resolve(process.cwd(), 'src/components'),
      _styles: path.resolve(process.cwd(), 'src/styles'),
      _images: path.resolve(process.cwd(), 'src/assets/images'),
      _constants: path.resolve(process.cwd(), 'src/constants'),
    },
    extensions: ['.js', '.jsx', '.json']
  },
  cache: isDev,
  stats: {
    entrypoints: false
  },
  node: {
    fs: 'empty',
    vm: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};
```

### Additional context

**Fixture code**
```js
import React from 'react';
import Button from './Button';

const btn = <Button>Click me</Button>;

export default btn;
```

**Component code**
```js
import React from 'react';
import PropTypes from 'prop-types';
import cn from 'classnames';
import CSSModules from 'react-css-modules';

import styles from './Button.scss';

const Button = ({
  className,
  children,
  type,
  appearance,
  size,
  isInverted,
  isDisabled,
}) => (
  <button
    styleName="root"
    className={cn(className, styles[appearance], styles[size], {
      [styles.inverted]: isInverted,
      [styles.disabled]: isDisabled,
    })}
    type={type}
  >
    {children}
  </button>
);

Button.propTypes = {
  className: PropTypes.string,
  children: PropTypes.oneOfType([
    PropTypes.node,
    PropTypes.element,
  ]),
  type: PropTypes.oneOf(['button', 'submit', 'reset']),
  appearance: PropTypes.oneOf(['success', 'light']),
  size: PropTypes.oneOf(['big', 'small']),
  isInverted: PropTypes.bool,
  isDisabled: PropTypes.bool,
};

Button.defaultProps = {
  type: 'button',
  appearance: 'success',
  size: 'small',
  isInverted: false,
  isDisabled: false,
};

export default CSSModules(Button, styles);
```

**Comment by michaelkutuzov** [comment]
### I found solution to this bug!

For all who will stuck in future:
Add to cosmos.config.json

```js
"globalImports": [
    "./src/styles/fonts.scss" // path to your file with connected fonts
  ]
```
In my case it is

```scss
@font-face {
  font-family: 'Circe';
  src:
    url('_styles/fonts/Circe/Circe-ExtraLight.woff') format('woff'),
    url('_styles/fonts/Circe/Circe-ExtraLight.woff2') format('woff2');
  font-weight: extralight;
  font-style: normal;
}

@font-face {
  font-family: 'Circe';
  src:
    url('_styles/fonts/Circe/Circe-Light.woff') format('woff'),
    url('_styles/fonts/Circe/Circe-Light.woff2') format('woff2');
  font-weight: light;
  font-style: normal;
}

@font-face {
  font-family: 'Circe';
  src:
    url('_styles/fonts/Circe/Circe-Regular.woff') format('woff'),
    url('_styles/fonts/Circe/Circe-Regular.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'Circe';
  src:
    url('_styles/fonts/Circe/Circe-Bold.woff') format('woff'),
    url('_styles/fonts/Circe/Circe-Bold.woff2') format('woff2');
  font-weight: bold;
  font-style: normal;
}

@font-face {
  font-family: 'Circe';
  src:
    url('_styles/fonts/Circe/Circe-ExtraBold.woff') format('woff'),
    url('_styles/fonts/Circe/Circe-ExtraBold.woff2') format('woff2');
  font-weight: extrabold;
  font-style: normal;
}

```
