### ISSUE TITLE
Yarn pnp incompatibility

### ISSUE THREAD

**Issue by DiFuks** [react-cosmos/react-cosmos#1386]
I get an error when running `yarn cosmos`:

```
Error: react-cosmos-plugin tried to access glob
```

And:

```
Error: react-cosmos-plugin tried to access resolve-from
```

This is solved by adding the following to yarnrc.yml :

```yml
packageExtensions:
  react-cosmos-plugin@*:
    dependencies:
      glob: "*"
      resolve-from: "*"
```

Not sure if this is the correct behavior
